name: tests unitaires
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
        os-version: ["22.04", "20.04"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
      - name: Install pytest
        run: pip3 install pytest
      - name: Run tests
        run: pytest TP1/test.py
      - name: Display branch name
        run: echo "Nom branche:${{ github.ref }}"
      - name: Display OS name
        run: echo "Nom OS:${{ runner.os }}."
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: echo "Version de python:${{ matrix.python-version }}"
      - name: Display OS version
        run: echo "Version de l'OS:${{ matrix.os-version }}"
      - name: Other OS information
        run: lsb_release -a
